{
  "hash": "1f587a639aebc121155112141f874924",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Aula 9\"\nformat: html\neditor: visual\nexecute: \n  error: false\n  warning: false\n---\n\n\n\n\n## Análise de múltiplos ensaios\n\nAo trabalhar com múltiplos ensaios, é possível analisá-los individualmente para observar uma tendência geral no comportamento dos tratamentos. No entanto, existem outras alternativas, como aplicar um modelo de regressão linear global ou extrair a informação global utilizando modelos mistos. Nesse caso, os ensaios são tratados como fator aleatório, ou seja, advêm de uma distribuição (população), e o objetivo é estimar os parâmetros para essa população.\n\nPara exemplificar esse caso, um conjunto de dados (`WhiteMoldSoybean`) presente no pacote **`r4pde`** será importado, mas antes o pacote deverá ser carregado.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(r4pde)\n\nwm <- WhiteMoldSoybean\n```\n:::\n\n\n### Análise exploratória\n\nVisualização gráfica da produtividade em função da incidência, por ensaio:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm %>% \n  ggplot (aes (inc, yld))+\n  geom_point()+\n  facet_wrap(~study)\n```\n\n::: {.cell-output-display}\n![](Aula-9.3_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n### Modelo linear global\n\nGráfico para visualizar os ensaios como um todo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm %>% \n  ggplot (aes (inc, yld))+\n  geom_point()+\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![](Aula-9.3_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nAjuste do modelo global:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmofo1 <- lm(yld ~ inc,\n            data = wm)\n```\n:::\n\n\nCálculo dos parâmetros para todos os ensaios\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mofo1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = yld ~ inc, data = wm)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1657.85  -594.50   -91.32   531.76  1693.15 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 3299.619     56.451  58.451  < 2e-16 ***\ninc           -9.261      2.108  -4.393 1.45e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 745.8 on 380 degrees of freedom\nMultiple R-squared:  0.04833,\tAdjusted R-squared:  0.04582 \nF-statistic:  19.3 on 1 and 380 DF,  p-value: 1.452e-05\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(mofo1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6141.545\n```\n\n\n:::\n:::\n\n\nPelo modelo ajustado para todos os ensaios globalmente, obtém-se um intercepto no eixo y igual a 3299.619 e o coeficiente de inclinação da reta igual a - 9.261. Para esse modelo o valor de AIC foi de 6141.54.\n\n### Modelo linear por ensaio\n\nGráfico para visualizar os ensaios individualmente:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm %>% \n  ggplot (aes (inc, yld, group = factor(study)))+\n  geom_point()+\n  geom_smooth(method = \"lm\", se = F)\n```\n\n::: {.cell-output-display}\n![](Aula-9.3_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nCálculo dos parâmetros para cada ensaio:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(broom)\nmofo2 <- wm %>% \n  group_by(study) %>% \n  do(broom::tidy(lm(.$yld ~ .$inc), conf.int=TRUE))\n\nmofo2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 70 × 8\n# Groups:   study [35]\n   study term        estimate std.error statistic  p.value conf.low conf.high\n   <dbl> <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n 1     1 (Intercept)  3329.       86.8      38.3  4.60e-13   3138.    3520.  \n 2     1 .$inc         -14.2       2.08     -6.85 2.78e- 5    -18.8     -9.64\n 3     2 (Intercept)  2682.       48.6      55.2  8.55e-15   2575.    2789.  \n 4     2 .$inc          -6.93      1.49     -4.66 6.89e- 4    -10.2     -3.66\n 5     3 (Intercept)  4017.       61.6      65.2  1.37e-15   3882.    4153.  \n 6     3 .$inc         -18.6       1.71    -10.9  3.11e- 7    -22.4    -14.9 \n 7     4 (Intercept)  2814.      151.       18.6  1.15e- 9   2481.    3147.  \n 8     4 .$inc         -43.5      16.8      -2.58 2.56e- 2    -80.5     -6.38\n 9     5 (Intercept)  3317.      234.       14.2  2.07e- 8   2802.    3832.  \n10     5 .$inc         -21.2       5.69     -3.72 3.36e- 3    -33.7     -8.67\n# ℹ 60 more rows\n```\n\n\n:::\n:::\n\n\nApós calcular os parâmetros para cada ensaio, é possível obter as suas médias. Para isso, existem dois caminhos.\n\n-   Opção 1:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- mofo2 %>% filter(term == \".$inc\")\nmean(df$estimate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -19.52932\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ny0 <- mofo2 %>% filter(term == \"(Intercept)\")\nmean(y0$estimate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3482.303\n```\n\n\n:::\n:::\n\n\n-   Opção 2:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmofo2 |> \n  filter(term == \".$inc\") |>\n  ungroup() |> \n  dplyr::select(estimate) |> \n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    estimate      \n Min.   :-43.455  \n 1st Qu.:-27.676  \n Median :-16.926  \n Mean   :-19.529  \n 3rd Qu.:-13.054  \n Max.   :  2.712  \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmofo2 %>% \n  filter(term == \"(Intercept)\")  %>% \n  ungroup() %>% \n  dplyr::select(estimate) %>% \n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    estimate   \n Min.   :1760  \n 1st Qu.:2863  \n Median :3329  \n Mean   :3482  \n 3rd Qu.:4080  \n Max.   :4923  \n```\n\n\n:::\n:::\n\n\nPela média dos modelos ajustados para casa ensaio, obtém-se um intercepto no eixo y igual a 3482.303 e o coeficiente de inclinação da reta igual a - 19.529.\n\nTambém é possível construir histogramas para cada um dos parâmetros.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- mofo2 %>% \n  filter(term == \"(Intercept)\") %>% \n  ggplot(aes(x = estimate))+\n  geom_histogram(bins = 8, color = \"white\", fill = \"gray50\")+\n  theme_r4pde()+\n  labs( x = \"Intercept\",\n        y = \"Frequency\")\n\np1\n```\n\n::: {.cell-output-display}\n![](Aula-9.3_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\np2 <- mofo2 %>% \n  filter(term == \".$inc\") %>%  \n  ggplot(aes(x = estimate))+\n  geom_histogram(bins = 8, color = \"white\", fill = \"gray50\")+\n  theme_r4pde()+\n  labs(x = \"Slope\", y = \"Frequency\")\n\np2\n```\n\n::: {.cell-output-display}\n![](Aula-9.3_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(patchwork)\n(p1+p2)\n```\n\n::: {.cell-output-display}\n![](Aula-9.3_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n### Modelo linear misto\n\nConstrução do modelo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lme4)\n\nmofo3 <- lmer(yld ~ inc + (inc | study), data = wm,\n              REML = F)\n```\n:::\n\n\nCálculo dos parâmetros:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mofo3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by maximum likelihood  ['lmerMod']\nFormula: yld ~ inc + (inc | study)\n   Data: wm\n\n     AIC      BIC   logLik deviance df.resid \n  5319.4   5343.1  -2653.7   5307.4      376 \n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-3.7078 -0.5991 -0.0295  0.5077  3.2364 \n\nRandom effects:\n Groups   Name        Variance  Std.Dev. Corr \n study    (Intercept) 557573.08 746.708       \n          inc             36.85   6.071  -0.29\n Residual              37228.73 192.947       \nNumber of obs: 382, groups:  study, 35\n\nFixed effects:\n            Estimate Std. Error t value\n(Intercept) 3455.432    128.063   26.98\ninc          -17.236      1.451  -11.88\n\nCorrelation of Fixed Effects:\n    (Intr)\ninc -0.300\noptimizer (nloptwrap) convergence code: 0 (OK)\nModel failed to converge with max|grad| = 0.416806 (tol = 0.002, component 1)\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(mofo3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5319.403\n```\n\n\n:::\n:::\n\n\nPelos resultados obtidos acima, observa-se que o intercepto no eixo y foi igual a 3455.432 e o coeficiente de inclinação da reta foi igual a - 17.236. Para o modelo linear misto, o AIC foi igual a 5319.403.\n\n\\\nCálculo dos intervalos de confiança, para o intercepto e coeficiente de inclinação da reta:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(mofo3, method = \"Wald\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %     97.5 %\n.sig01              NA         NA\n.sig02              NA         NA\n.sig03              NA         NA\n.sigma              NA         NA\n(Intercept) 3204.43403 3706.43096\ninc          -20.08046  -14.39219\n```\n\n\n:::\n:::\n\n\n\\\nAo comparar os modelos gerados, nota-se que os valores dos parâmetros são bem próximos. No entanto, ao comparar os valores de AIC, o menor valor é obtido para o modelo linear misto, sugerindo que este método se ajusta melhor aos dados do exemplo.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}