{
  "hash": "cbe516091847e92e58bd1716cd7741ce",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat: html\neditor: visual\nexecute: \n  warning: false\n  error: false\n---\n\n\n# Aula 5\n\nNesta aula, serão analisados e interpretados os valores das notas das duas primeiras atividades avaliativas da disciplina FIP 606.\\\n\n## Carregando os pacotes\n\nInicialmente, serão carregados os pacotes necessários para o desenvolvimento das análises.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gsheet)\nlibrary(tidyverse)\nlibrary(ggthemes)\nlibrary(patchwork)\n```\n:::\n\n\n## Obtenção e visualização dos dados\n\nOs dados utilizados foram disponibilizados em uma planilha online e serão importados utilizando a função `gsheet2tbl` (**`gsheet`**):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- gsheet2tbl(\"https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=1092065531\")\n```\n:::\n\n\n\\\nPara uma rápida visualização dos dados importados, será aplicada a função `glimpse` (**`dplyr`**):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 44\nColumns: 3\n$ prova  <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …\n$ pontos <dbl> 10, 13, 12, 6, 14, 12, 14, 8, 14, 10, 10, 13, 9, 14, 9, 14, 12,…\n$ nota   <dbl> 71.40, 92.90, 85.70, 42.90, 100.00, 85.70, 100.00, 57.10, 100.0…\n```\n\n\n:::\n:::\n\n\n\\\nAo avaliar o arquivo gerado acima, é possível notar que a coluna \"prova\" está definida como númerica (\"*dbl*\"), portanto será necessário transformá-la para um novo tipo de dado (fator - \"*fct*\"), a fim de viabilizar o decorrer da atividade.\\\nPara isso, será utilizada a função `as.factor`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados$prova <- as.factor(dados$prova)\nglimpse(dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 44\nColumns: 3\n$ prova  <fct> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …\n$ pontos <dbl> 10, 13, 12, 6, 14, 12, 14, 8, 14, 10, 10, 13, 9, 14, 9, 14, 12,…\n$ nota   <dbl> 71.40, 92.90, 85.70, 42.90, 100.00, 85.70, 100.00, 57.10, 100.0…\n```\n\n\n:::\n:::\n\n\n## Sumário estatístico\n\nPara um breve sumário estatístico dos valores das avaliações, será utilizada a coluna \"nota\" (normalizada previamente). Será feito o agrupamento dos valores de acordo com a \"prova\", utilizando a função `group_by`. Em seguida, será aplicada a função `summarise` para a obtenção de algumas estatísticas descritivas. Ambas as funções pertencem ao pacote **`dplyr`**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados %>% group_by(prova) %>%\n  summarise(n = n(),\n            mín = min(nota),\n            máx = max(nota),\n            mean = mean(nota),\n            sd = sd(nota),\n            median = median(nota))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  prova     n   mín   máx  mean    sd median\n  <fct> <int> <dbl> <dbl> <dbl> <dbl>  <dbl>\n1 1        22  42.9   100  79.5  19.0   85.7\n2 2        22  43.8   100  79.3  19.7   84.4\n```\n\n\n:::\n:::\n\n\n## Visualização gráfica dos valores de nota\n\n### Histograma geral\n\nInicialmente, será feito um gráfico do tipo histograma para conhecer a distribuição geral das notas. Será utilizada a função `geom_histogram` (**`ggplot2`**).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados %>%\n  ggplot(aes(nota))+\n  geom_histogram(binwidth = 3)+\n  labs(x = \"Nota\",\n       y = \"Frequência\")+\n  lims(x = c(NA,100),\n       y = c(0,NA))+\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Aula-5_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n### Boxplot por avaliação\n\nPara visualizar a distribuição dos valores das notas em função da prova, será construído um gráfico do tipo boxplot (`geom_boxplot`) acrescido de pontos (`geom_jitter`), representando as observações individuais.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados %>%\n  ggplot(aes(prova, nota))+\n  geom_boxplot(width = 0.4)+\n  geom_jitter(width = 0.2, alpha = 0.5)+\n  labs(x = \"Avaliação\",\n       y = \"Nota\")+\n  lims(y=c(30,110))+\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Aula-5_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n### Histograma por avaliação\n\nPrimeiro, será necessário criar novos dataframes em função da avaliação (1 ou 2).\\\nPara isso, as colunas \"prova\" e \"nota\" serão selecionadas (`select`, pacote **`dplyr`**) e em seguida, o filtro (`filter`, pacote **`dplyr`**) será aplicado na coluna \"prova\":\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados1 <-    \n  dados %>% select(prova, nota) %>%   \n  filter(prova == \"1\")  \n\n\ndados2 <-   \n  dados %>% select(prova, nota) %>%    \n  filter(prova == \"2\")\n```\n:::\n\n\n#### Histograma da avaliação 1:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- mean(dados1$nota)\n\ng1 <- dados1 %>%\n  ggplot(aes(nota))+\n  geom_histogram(color = \"white\", bins =5, fill = \"tomato1\", alpha = 0.9)+\n  geom_vline(xintercept = c(m1), alpha = 0.9, linetype = \"dashed\", linewidth = 0.9, colour = \"coral4\")+\n  annotate(\"text\", x = 70, y = 10, label = \"Média\")+\n  labs(x = \"Nota\",\n       y = \"Frequência\")+\n  ylim(c(0, 15))+\n  coord_fixed(ratio = 7)+\n  scale_x_continuous(breaks = seq(20,105,10))+\n  ggtitle(\"Prova 1\")+\n  theme_classic()+\n  theme(plot.title = element_text(vjust = 3))\n\ng1\n```\n\n::: {.cell-output-display}\n![](Aula-5_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n#### Histograma da avaliação 2:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2 <- mean(dados2$nota)\n\ng2 <- dados2 %>%\n  ggplot(aes(nota))+\n  geom_histogram(color = \"white\", bins =5, fill = \"navy\", alpha = 0.9)+\n  geom_vline(xintercept = c(m2), alpha = 0.9, linetype = \"dashed\", linewidth = 0.9, colour = \"skyblue2\")+\n  annotate(\"text\", x = 70, y = 10, label = \"Média\")+\n  labs(x = \"Nota\",\n       y = \"Frequência\")+\n  ylim(c(0, 15))+\n  ggtitle(\"Prova 2\")+\n  coord_fixed(ratio = 7)+\n  scale_x_continuous(breaks = seq(20,105,10))+\n  theme_classic()+\n  theme(plot.title = element_text(vjust = 3))\n\ng2\n```\n\n::: {.cell-output-display}\n![](Aula-5_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n#### Histogramas combinados:\n\nPara combinar os histogramas individuais em uma única imagem, será aplicado o pacote **`patchwork`**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(g1+g2)\n```\n\n::: {.cell-output-display}\n![](Aula-5_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n## Interpretação\n\nEm ambas as atividades, foram avaliadas 22 amostras (provas). Os gráficos demonstram que as notas mais frequentes estiveram entre aproximadamente 80 e 100, nas duas avaliações. Na primeira avaliação, as notas variaram de 42.90 a 100, com valor médio próximo a 79.5 (± 19) e valor mediano de 85.7. Na segunda avaliação, as notas variaram de 43.75 a 100, com média próxima de 79.2 (± 19.7) e mediana de 84.3. Comparando os valores médios das duas avaliações, os estudantes apresentaram desempenho similar.\n\n\\_\\_\\_\\_\\_\n\n\n::: {.cell}\n\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}