project:
  type: website
  output-dir: docs

website:
  title: "FIP 606 | Caio M."
  favicon: fig1.png

  navbar:
    pinned: true
    logo: fig1.png
    
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Aulas iniciais"
        contents:
          - Aula 1.qmd
          - Aula 2.qmd
          - Aula 3.qmd
      - section: "Análises"
        contents:
          - Aula 10.qmd

format:
  html:
    theme: navbars
    css: styles.css
    toc: true

editor: visual

