project:
  type: website
  output-dir: docs

execute: 
  cache: true
  freeze: auto

website:
  title: "FIP 606 | Caio M."
  favicon: fig1.png
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    left: "Caio M. Pereira, 2024"
    right:
      - icon: github
        href: https://github.com/caio-mtts

  navbar:
    pinned: true
    logo: fig1.png
    
    left:
      - href: index.qmd
        text: Home
        
    right:
      - icon: envelope-at
        href: mailto:caio.mattos@ufv.br
      - icon: github
        href: https://github.com/caio-mtts
      - icon: linkedin
        href: https://www.linkedin.com/in/caio-mattos-10001/


  sidebar:
    style: "docked"
    search: true
    border: true
    collapse-level: 1
    contents:
      - href: about.qmd
        text: Sumário
      - section: "Aula 01"
        contents:
          - href: Aula 1.1.qmd
            text: Criação de projetos, documentos e conjunto de dados
          - href: Aula 1.2.qmd
            text: Manipulações de dados
      - section: "Aula 02"
        contents:
          - href: Aula 2.1.qmd
            text: Importação de dados
          - href: Aula 2.2.qmd
            text: Importação de dados e criação de gráficos simples
      - section: "Aula 03"
        contents:
          - href: Aula 3.qmd
            text: Estatísticas descritivas e construção de gráficos simples
      - section: "Aula 04"
        contents:
          - href: Aula 4.1.qmd
            text: Uso do datapasta
          - href: Aula 4.2.qmd
            text: Tabela de contingência
      - section: "Aula 05"
        contents:
          - href: Aula 5.qmd
            text: Atividade prática
      - section: "Aula 06"
        contents:
          - href: Aula 6.1.qmd
            text: Estatística inferencial - Teste t
          - href: Aula 6.2.qmd
            text: Estatística inferencial - Análise de variância
      - section: "Aula 07"
        contents:
          - href: Aula 7.1.qmd
            text: Estatística inferencial - Análise de variância
          - href: Aula 7.2.qmd
            text: Estatística inferencial - Alternativas de análise
          - href: Aula 7.3.qmd
            text: Estatística inferencial - Experimento fatorial
      - section: "Aula 08"
        contents:
          - href: Aula 8.1.qmd
            text: Estatística inferencial - Experimento em DBC
          - href: Aula 8.2.qmd
            text: Curva de progresso da doença
      - section: "Aula 09"
        contents:
          - href: Aula 9.1.qmd
            text: Estatística inferencial - Experimento em parcelas subdivididas
          - href: Aula 9.2.qmd
            text: Estatística inferencial - Regressão linear
          - href: Aula 9.3.qmd
            text: Estatística inferencial - Análise de múltiplos ensaios
      - section: "Aula 10"
        contents:
          - href: Aula 10.1.qmd
            text: Análise de correlação
          - href: Aula 10.2.qmd
            text: Regressão linear de segunda ordem (quadrática)
          - href: Aula 10.3.qmd
            text: Modelo não-linear - Cálculo de EC50
      - section: "Aula 11"
        contents:
          - href: Aula 11.qmd
            text: Construção de gráficos com R

format:
  html:
    theme: navbars
    css: styles.css
    toc: true

editor: visual

