{
  "hash": "ecccb6ec9c6bf78e5e531c8ce9febeef",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Aula 6 - Estatísticas inferenciais: teste-t e ANOVA\"\nformat: html\neditor: visual\nexecute: \n  error: false\n  warning: false\neditor_options: \n  chunk_output_type: console\n---\n\n\n# Aula 6\n\nNesta aula serão apresentados alguns passos para condução da estatística inferencial. Inicialmente, serão conduzidos teste-t e, brevemente, alguns passos para realizar uma análise de variância (ANOVA).\n\n# Carregando os pacotes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gsheet)\nlibrary(tidyverse)\nlibrary(report)\n```\n:::\n\n\nPacotes utilizados para realizar ANOVA:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\nlibrary(multcomp)\nlibrary(multcompView)\nlibrary(DHARMa)\nlibrary(performance)\n```\n:::\n\n\n# Análise inferencial - Teste t\n\n## Obtenção dos dados\n\nOs dados serão importados de uma planilha online, utilizado a ferramenta `gsheet2tbl` (**`gsheet`**). O conjunto de dados é referente a avaliação do efeito da suplementação de magnésio (Mg~2~) sobre o comprimento de lesões.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmg <- gsheet2tbl(\"https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=983033137\")\n\nglimpse(mg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 20\nColumns: 3\n$ trat <chr> \"Mg2\", \"Mg2\", \"Mg2\", \"Mg2\", \"Mg2\", \"Mg2\", \"Mg2\", \"Mg2\", \"Mg2\", \"M…\n$ rep  <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10\n$ comp <dbl> 9.00, 12.50, 10.00, 8.00, 13.20, 11.00, 10.80, 9.50, 10.80, 10.40…\n```\n\n\n:::\n:::\n\n\n## Análise dos dados\n\nInicialmente, será feito um gráfico do tipo boxplot para analisarmos o conjunto de dados visualmente.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmg %>% \n  ggplot(aes(trat, comp))+\n  geom_boxplot(width = 0.5)\n```\n\n::: {.cell-output-display}\n![](Aula-6_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nO gráfico gerado sugere que há diferença no tamanho das lesões em função do tratamento avaliado. Onde a suplementação com Mg~2~ parece possuir efeito desejável, reduzindo o comprimento das lesões.\\\nAlém, o gráfico indica que os dados possuem distribuição normal, pois há simetria em ambos os retângulos; e que também homocedasticidade (homogeneidade das variâncias), já que os dois retângulos possuem tamanho semelhante.\n\n## Conversão dos dados\n\nAntes de realizar o teste-t será preciso transformar a tabela para o formato largo (cada tratamento em uma coluna), para isso será utilizada a função `pivot_wider` (**`tidyr`**):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmg2 <- mg %>%\n  pivot_wider(names_from = trat,\n              values_from = comp)\n\nglimpse(mg2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 10\nColumns: 3\n$ rep     <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10\n$ Mg2     <dbl> 9.0, 12.5, 10.0, 8.0, 13.2, 11.0, 10.8, 9.5, 10.8, 10.4\n$ control <dbl> 13.72, 15.91, 15.70, 14.20, 15.90, 16.54, 18.00, 14.40, 16.41,…\n```\n\n\n:::\n:::\n\n\n## Teste-t\n\n### Teste-t para duas amostras independentes\n\nCom base no conjunto de dados recém transformado, será feito um teste t (função `t.test`, nativa do R) para duas amostras independentes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(mg2$Mg2, mg2$control)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  mg2$Mg2 and mg2$control\nt = -8.1549, df = 17.354, p-value = 2.423e-07\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -6.490393 -3.825607\nsample estimates:\nmean of x mean of y \n   10.520    15.678 \n```\n\n\n:::\n:::\n\n\nA partir do resultado do teste, podemos concluir há diferença significativa entre os tratamentos, pois o valor de P foi extretamente baixo (\\< 0.01).\n\n#### Verificação das premissas\n\nPara termos confiança no teste realizado é preciso saber se os dados atendem algumas premissas: se há normalidade entre os conjuntos; e se os conjuntos possuem mesma variância.\n\n#### Teste de normalidade:\n\n-   Histogramas\\\n    Uma forma de se avaliar a normalidade visualmente é por meio de histograma:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(mg2$control)\n```\n\n::: {.cell-output-display}\n![](Aula-6_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code}\nhist(mg2$Mg2)\n```\n\n::: {.cell-output-display}\n![](Aula-6_files/figure-html/unnamed-chunk-7-2.png){width=672}\n:::\n:::\n\n\n-   Q-Q Plot de normalidade\n\n    Outra opção é por meio de Q-Q plots:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(mg2$control)\nqqline(mg2$control)\n```\n\n::: {.cell-output-display}\n![](Aula-6_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(mg2$Mg2)\nqqline(mg2$Mg2)\n```\n\n::: {.cell-output-display}\n![](Aula-6_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n-   Avaliação estatística\n\n    A avaliação também pode ser feita utilizando testes estatísticos. Nesse caso, será aplicada a função `shapiro.test` (nativa do R):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(mg2$control)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  mg2$control\nW = 0.93886, p-value = 0.5404\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(mg2$Mg2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  mg2$Mg2\nW = 0.97269, p-value = 0.9146\n```\n\n\n:::\n:::\n\n\nAmbas as metodologias demonstram que os dados possuem distribuição normal. Os histogramas possuem formato típico de um conjunto de dados normais. Nos Q-Q Plots, é possível notar que os pontos estão próximo a linha de normalidade. E pelos testes de Shapiro Wilk, não se rejeita a hipótese nula (de normalidade), já que valor de P é maior que o nível de significância adotado (⍺ = 5%).\n\n#### Teste de homogeneidade\n\nPara avaliação da homogeneidade entre as variâncias será utilizada a função `var.test` (também nativa do R):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar.test(mg2$control, mg2$Mg2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test to compare two variances\n\ndata:  mg2$control and mg2$Mg2\nF = 0.67654, num df = 9, denom df = 9, p-value = 0.5698\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.1680428 2.7237436\nsample estimates:\nratio of variances \n         0.6765394 \n```\n\n\n:::\n:::\n\n\nCom o resultado do teste não rejeitamos a hipótese nula (de homogeneidade entre as amostras), pois o valor de probabilidade é superior a 5%. Logo, os tratamentos possuem mesma variância.\\\n\\\nCom isso (dados normais, com variâncias homogêneas), podemos confiar no teste-t realizado.\n\n#### Apresentação dos resultados\n\nA função `report` (**`report`**) pode ser utilizada para gerar um modelo de texto, reportando os resultados obtidos. Para isso atribuímos o teste-t a um objeto e em sequência executamos a função.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nteste1 <- t.test(mg2$Mg2, mg2$control)\nreport(teste1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEffect sizes were labelled following Cohen's (1988) recommendations.\n\nThe Welch Two Sample t-test testing the difference between mg2$Mg2 and\nmg2$control (mean of x = 10.52, mean of y = 15.68) suggests that the effect is\nnegative, statistically significant, and large (difference = -5.16, 95% CI\n[-6.49, -3.83], t(17.35) = -8.15, p < .001; Cohen's d = -3.65, 95% CI [-5.12,\n-2.14])\n```\n\n\n:::\n:::\n\n\n### Teste-t para duas amostras dependentes\n\nPara demonstrar a aplicação do test-t pareado (ou para amostras dependentes), utilizaremos um conjunto de dados no qual há resultados de avaliação de doenças antes e após o uso de uma escala de doenças, logo o objetivo será determinar se o uso da escala desempenha algum efeito sobre as avaliações.\\\n\n### Quando há distribuição normal\n\n#### Obtenção, visualização e seleção dos dados\n\nOs dados serão obtidos de uma planilha excel:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nescala <- readxl::read_excel(\"dados-diversos.xlsx\",\n                             sheet = \"escala\")\n\nglimpse(escala)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 20\nColumns: 7\n$ assessment       <chr> \"Unaided\", \"Unaided\", \"Unaided\", \"Unaided\", \"Unaided\"…\n$ rater            <chr> \"A\", \"B\", \"C\", \"D\", \"E\", \"F\", \"G\", \"H\", \"I\", \"J\", \"A\"…\n$ acuracia         <dbl> 0.8092131, 0.7219848, 0.5595983, 0.8175313, 0.7476691…\n$ precisao         <dbl> 0.8262697, 0.7284040, 0.7149415, 0.8187018, 0.7532589…\n$ vies_geral       <dbl> 0.9793570, 0.9911874, 0.7827190, 0.9985702, 0.9925792…\n$ vies_sistematico <dbl> 1.1872167, 0.9217054, 1.1600785, 0.9481874, 1.1038873…\n$ vies_constante   <dbl> 0.1123982, -0.1055045, 0.7301412, -0.0056930, 0.07194…\n```\n\n\n:::\n:::\n\n\nEm seguida, será feito um boxplot para rápida visualização do conjunto de dados:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nescala %>%\n  ggplot(aes(assessment, acuracia))+\n  geom_boxplot(width = 0.4)\n```\n\n::: {.cell-output-display}\n![](Aula-6_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nPara condução dos testes, serão selecionadas as colunas \"assessment\", \"rater\" e \"acuracia\", que serão colocados no formato largo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nescala2 <- escala %>%\n  dplyr::select( assessment, rater, acuracia) %>% \n  pivot_wider(names_from = assessment,\n              values_from = acuracia)\n\nglimpse(escala2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 10\nColumns: 3\n$ rater   <chr> \"A\", \"B\", \"C\", \"D\", \"E\", \"F\", \"G\", \"H\", \"I\", \"J\"\n$ Unaided <dbl> 0.8092131, 0.7219848, 0.5595983, 0.8175313, 0.7476691, 0.69491…\n$ Aided1  <dbl> 0.9067211, 0.9126980, 0.9148087, 0.9598576, 0.9593181, 0.90277…\n```\n\n\n:::\n:::\n\n\n#### Testar as premissas\n\n#### Teste de normalidade\n\nA avaliação da normalidade será feita estatisticamente, pelo teste de Shapiro Wilk, com valor de significância (⍺) de 5%:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(escala2$Unaided)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  escala2$Unaided\nW = 0.87462, p-value = 0.1131\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(escala2$Aided1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  escala2$Aided1\nW = 0.92775, p-value = 0.4261\n```\n\n\n:::\n:::\n\n\nPara ambos os tratamentos há normalidade, já que os valores de P foram superiores a 5%.\\\n\n#### Teste de homogeneidade\n\nPara avaliação da homogeneidade entre as variâncias, usaremos o teste de variância:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar.test(escala2$Unaided, escala2$Aided1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test to compare two variances\n\ndata:  escala2$Unaided and escala2$Aided1\nF = 5.8683, num df = 9, denom df = 9, p-value = 0.01461\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n  1.457601 23.625712\nsample estimates:\nratio of variances \n          5.868293 \n```\n\n\n:::\n:::\n\n\nO teste de variância demonstra que não há homogeneidade entre os conjuntos de dados, pois o valor de P é menor que 0,05 (5%). Logo, será preciso indicar no teste t que há heterogeneidade.\\\n\n#### Teste t pareado\n\nComo demonstrado acima, os dados possuem distribuição normal, portanto ainda é possível utilizar um teste paramétrico. No entanto, não há homogeneidade de variâncias, o que precisará ser indicado na construção da função.\n\nPara executar o teste t pareado utiliza-se a mesma função (`t.test`), incluindo dois parâmetros:\n\n-   `paired = TRUE`, para indicar amostras dependentes (ou pareadas);\n\n-   e `var.equal = FALSE` , para indicar heterocedasticidade.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(escala2$Aided1,escala2$Unaided,\n       paired = TRUE,\n       var.equal = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  escala2$Aided1 and escala2$Unaided\nt = 5.9364, df = 9, p-value = 0.000219\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 0.1144707 0.2554241\nsample estimates:\nmean difference \n      0.1849474 \n```\n\n\n:::\n:::\n\n\nCom o teste, é possível concluir que o uso da escala teve efeito sobre a acurácia dos avaliadores (P-valor = 0.000219), onde foi perceptível um aumento de acurácia após o uso da assistência.\\\n\n### Quando **não** há distribuição normal: teste não paramétrico\n\nPara demonstrar essa situação será utilizado um conjunto de dados similar ao exemplo anterior. No entanto, com alguns valores alterados para não possuir mais distribuição normal.\n\n#### Obtenção, visualização e seleção dos dados\n\n\n::: {.cell}\n\n```{.r .cell-code}\nescala3 <- gsheet2tbl(\"https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=1729131173\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nescala3 %>%\n  ggplot(aes(assessment, acuracia))+\n  geom_boxplot(width = 0.4)\n```\n\n::: {.cell-output-display}\n![](Aula-6_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nescala4 <- escala3 %>%\n  dplyr::select(assessment, rater, acuracia) %>% \n  pivot_wider(names_from = assessment,\n              values_from = acuracia)\n```\n:::\n\n\n#### Testar as premissas\n\n#### Teste de normalidade\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(escala4$Unaided)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  escala4$Unaided\nW = 0.7748, p-value = 0.007155\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(escala4$Aided1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  escala4$Aided1\nW = 0.92852, p-value = 0.4335\n```\n\n\n:::\n:::\n\n\nO teste mostra que não há normalidade para o tratamento \"unaided\" (valor de p \\< 0.05), logo será preciso realizar um **teste não paramétrico**.\\\n\n#### Teste de Wilcox\n\nComo o conjunto de dados não possui distribuição normal, será utilizado o teste de Wilcox (`wilcox.test`). Um teste não paramétrico para amostras dependentes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(escala4$Aided1,\n            escala4$Unaided,\n            paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  escala4$Aided1 and escala4$Unaided\nV = 55, p-value = 0.005889\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\nSimilarmente a situação de normalidade, o teste de Wilcox demonstra que há diferença significativa entre as amostras (P = 0.005 \\< ⍺ = 0.05), onde o uso da escala influencia positivamente a acurácia dos avaliadores.\n\n## Análise de Variância (ANOVA)\n\nA análise de variância é adotada quando desejamos comparar três ou mais variáveis quantitativas independentes e que possuem distribuição normal.\n\n### Exemplo 1) sem diferença estatística\n\n### Análise exploratória - obtenção e visualização dos dados\n\nOs dados serão importados de uma planilha excel e apresentam a taxa de crescimento micelial de 5 espécies de *Fusarium*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmicelial <- readxl::read_excel(\"dados-diversos.xlsx\",\n                               sheet = \"micelial\")\nglimpse(micelial)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 42\nColumns: 3\n$ especie <chr> \"Fasi\", \"Fasi\", \"Fasi\", \"Fasi\", \"Fasi\", \"Fasi\", \"Faus\", \"Faus\"…\n$ rep     <dbl> 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 7, 8, 9,…\n$ tcm     <dbl> 1.50, 1.59, 1.52, 1.52, 1.24, 1.29, 1.52, 1.25, 1.27, 0.88, 1.…\n```\n\n\n:::\n\n```{.r .cell-code}\n#tcm = taxa de crescimento micelial\n```\n:::\n\n\nPara visualização dos dados, será construído um simples gráfico de pontos (`geom_jitter`) ao invés de boxplots (`geom_boxplot`).\\\nComo cada tratamento possui em torno de 10 respostas (pontos), esse tipo de gráfico já é suficiente para visualizar a distribuição dos valores.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmicelial %>% \n  ggplot(aes(especie, tcm))+\n  geom_jitter(width = 0.1)\n```\n\n::: {.cell-output-display}\n![](Aula-6_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n### Análise inferencial - ANOVA\n\n#### Construção do modelo\n\nAntes de realizar a ANOVA, é preciso ajustar um modelo linear (lm). Para isso, será utilizada a função `lm`. Nessa função, os modelos são construídos simbolicamente: com a variável dependente, seguida de um `~`, e a variável independente. Em seguida, informamos no argumento `data` qual o conjunto de dados (data frame) que contém as variáveis do modelo.\\\nEssa fórmula será atribuída a um objeto.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- lm(tcm ~ especie, data = micelial)\n```\n:::\n\n\n#### Avaliação das premissas\n\nUma vez construído o modelo, é necessário determinar se os dados satisfazem as premissas para proceder a análise de variância.\n\n#### Normalidade\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(m1$residuals)\n```\n\n::: {.cell-output-display}\n![](Aula-6_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n\n```{.r .cell-code}\nshapiro.test(m1$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  m1$residuals\nW = 0.95101, p-value = 0.07022\n```\n\n\n:::\n:::\n\n\nTanto visualmente, quanto estatisticamente, os resíduos possuem distribuição normal.\n\n#### Homogeneidade\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbartlett.test(tcm ~ especie, data = micelial)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  tcm by especie\nBartlett's K-squared = 3.1169, df = 4, p-value = 0.5385\n```\n\n\n:::\n:::\n\n\nO teste de Barlett indica que o conjunto de dados possui homogeneidade de variância.\n\n#### ANOVA\n\nO modelo criado é utilizado dentro da função `anova`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: tcm\n          Df  Sum Sq Mean Sq F value Pr(>F)\nespecie    4 0.46917 0.11729   1.983 0.1173\nResiduals 37 2.18853 0.05915               \n```\n\n\n:::\n:::\n\n\nCom esse conjunto de dados, é possível concluir que as taxas de crescimento micelial das espécies de *Fusarium* não diferem significativamente entre si (F = 0.1173 \\> ⍺ = 0.05).\n\n\\\nA função `summary` será aplicada para produzir um sumário dos resultados do modelo ajustado.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = tcm ~ especie, data = micelial)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.45933 -0.20028  0.06067  0.14017  0.36167 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  1.44333    0.09929  14.537   <2e-16 ***\nespecieFaus -0.28500    0.14042  -2.030   0.0496 *  \nespecieFcor -0.28400    0.11748  -2.417   0.0207 *  \nespecieFgra -0.30000    0.14042  -2.137   0.0393 *  \nespecieFmer -0.14222    0.12818  -1.110   0.2744    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.2432 on 37 degrees of freedom\nMultiple R-squared:  0.1765,\tAdjusted R-squared:  0.08751 \nF-statistic: 1.983 on 4 and 37 DF,  p-value: 0.1173\n```\n\n\n:::\n:::\n\n\nO intercepto indica a média do primeiro nível (*Fasi* = 1.43) e em seguida são apresentados as diferenças para cada nível em relação ao primeiro. Por exemplo, a média da taxa de crescimento micelial do nível *Faus* será 1.15 (1.43 - 0.28).\\\n\\\n\nO intercepto pode ser removido incluindo `-1` na construção do modelo. Dessa forma, serão apresentados os valores de média de cada nível:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2 <- lm(tcm ~ especie - 1, data = micelial)\nsummary(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = tcm ~ especie - 1, data = micelial)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.45933 -0.20028  0.06067  0.14017  0.36167 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \nespecieFasi  1.44333    0.09929   14.54  < 2e-16 ***\nespecieFaus  1.15833    0.09929   11.67 5.85e-14 ***\nespecieFcor  1.15933    0.06280   18.46  < 2e-16 ***\nespecieFgra  1.14333    0.09929   11.52 8.56e-14 ***\nespecieFmer  1.30111    0.08107   16.05  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.2432 on 37 degrees of freedom\nMultiple R-squared:  0.9668,\tAdjusted R-squared:  0.9623 \nF-statistic: 215.7 on 5 and 37 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n### Exemplo 2) com diferença estatística\n\nUm conjunto de dados similar ao anterior será importado de uma planilha online. Nesse novo conjunto os dados foram alterados para apresentarem diferença estatística e avançarmos na análise inferencial.\\\n\n### Análise exploratória - obtenção e visualização dos dados\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmicelial2 <- gsheet2tbl(\"https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=959387827\")\n\n#tcm = taxa de crescimento micelial\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmicelial2 %>% \n  ggplot(aes(especie, tcm))+\n  geom_jitter(width = 0.1)\n```\n\n::: {.cell-output-display}\n![](Aula-6_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n#### Construção do modelo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3 <- lm(tcm ~ especie, data = micelial2)\n```\n:::\n\n\n#### Avaliação das premissas\n\n#### Normalidade\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(m3$residuals)\n```\n\n::: {.cell-output-display}\n![](Aula-6_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n\n```{.r .cell-code}\nshapiro.test(m3$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  m3$residuals\nW = 0.9821, p-value = 0.8782\n```\n\n\n:::\n:::\n\n\nTanto visualmente, quanto estatisticamente, os resíduos possuem distribuição normal.\n\n#### Homogeneidade\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbartlett.test(tcm ~ especie, data = micelial2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  tcm by especie\nBartlett's K-squared = 4.4367, df = 4, p-value = 0.3501\n```\n\n\n:::\n:::\n\n\nO teste de Barlett indica que o conjunto de dados possui homogeneidade de variância.\n\n### Análise inferencial - ANOVA\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: tcm\n          Df  Sum Sq Mean Sq F value    Pr(>F)    \nespecie    4 1.46958 0.36739  19.629 2.028e-07 ***\nResiduals 25 0.46792 0.01872                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = tcm ~ especie, data = micelial2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.23667 -0.09667  0.01583  0.08833  0.28333 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  1.57167    0.05585  28.140  < 2e-16 ***\nespecieFaus -0.33500    0.07899  -4.241 0.000266 ***\nespecieFcor -0.25000    0.07899  -3.165 0.004047 ** \nespecieFgra -0.66000    0.07899  -8.356 1.05e-08 ***\nespecieFmer -0.14500    0.07899  -1.836 0.078317 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1368 on 25 degrees of freedom\nMultiple R-squared:  0.7585,\tAdjusted R-squared:  0.7199 \nF-statistic: 19.63 on 4 and 25 DF,  p-value: 2.028e-07\n```\n\n\n:::\n:::\n\n\nCom esse novo conjunto de dados, conclui-se que as taxas de crescimento micelial das espécies de *Fusarium* diferem significativamente entre si (F = 2.2 \\* 10^-7^ \\> ⍺ = 0.05). O próximo passo será adotar um teste de comparação de médias para conhecer como as espécies se agrupam quanto as taxas de crescimento.\n\n### Comparação de médias - Teste de Tukey\n\nPara realizar o teste de Tukey, utilizaremos os pacotes `emmeans`, `multcomp` e `multcompview`.\n\nInicialmente, a função `emmeans` (pacote `emmeans`) será aplicada para estimar as médias de um fator específico em um modelo linear. O resultado será atribuído a um objeto.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedias1 <- emmeans(m3, ~ especie)\n```\n:::\n\n\nPara comparação de médias - Teste de Tukey - será utilizada a função `cld` (pacote `multcomp`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncld(medias1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n especie emmean     SE df lower.CL upper.CL .group\n Fgra     0.912 0.0559 25    0.797     1.03  1    \n Faus     1.237 0.0559 25    1.122     1.35   2   \n Fcor     1.322 0.0559 25    1.207     1.44   2   \n Fmer     1.427 0.0559 25    1.312     1.54   23  \n Fasi     1.572 0.0559 25    1.457     1.69    3  \n\nConfidence level used: 0.95 \nP value adjustment: tukey method for comparing a family of 5 estimates \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n:::\n\n\nCom o resultado obtido a um nível de significância de 5%, interpretamos que *Fgra* possui a menor taxa de crescimento, em comparação as demais espécies. *Faus*, *Fcor* e *Fmer* possuem taxa de crescimento estatisticamente similar. Já *Fmer* e *Fasi* são estatisticamente similares e possuem a maior taxa de crescimento.\n\n### Alternativas para verificação das premissas\n\n#### Pacote `DHARMa`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(simulateResiduals(m3))\n```\n\n::: {.cell-output-display}\n![](Aula-6_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\n#### Pacote `performance`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(performance)\ncheck_normality(m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOK: residuals appear as normally distributed (p = 0.878).\n```\n\n\n:::\n\n```{.r .cell-code}\ncheck_heteroscedasticity(m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOK: Error variance appears to be homoscedastic (p = 0.880).\n```\n\n\n:::\n\n```{.r .cell-code}\ncheck_model(m3)\n```\n\n::: {.cell-output-display}\n![](Aula-6_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}