{
  "hash": "b2707c96b47e47afa0786df1eec0c68f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Aula 7 - Estatística inferencial: ANOVA\"\nauthor: \"Caio\"\nformat: html\neditor: visual\nexecute: \n  error: false\n  warning: false\n---\n\n\n# Aula 07\n\n## Carregando os pacotes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gsheet)\nlibrary(tidyverse)\nlibrary(performance)\nlibrary(DHARMa)\nlibrary(emmeans)\nlibrary(multcomp)\nlibrary(multcompView)\n```\n:::\n\n\n## Exemplo de Análise de Variância (ANOVA)\n\nPara realizar a análise de variância (ANOVA), será carregado um conjunto de dados presente no R (conjunto `InsectSprays`), que será atribuído a um objeto:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninseticida <- InsectSprays\n\ninseticida %>% \n  count(spray)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  spray  n\n1     A 12\n2     B 12\n3     C 12\n4     D 12\n5     E 12\n6     F 12\n```\n\n\n:::\n:::\n\n\nCom a fórmula `count`, identificamos que nesse conjunto de dados há um fator (inseticida), com 6 níveis (tipos de inseticidas), cada nível com 12 observações.\\\n\n## Explorando o conjunto\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninseticida %>%\n  ggplot(aes(spray, count))+\n  geom_boxplot(width = 0.5)\n```\n\n::: {.cell-output-display}\n![](Aula-7_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nCom o boxplot gerado, é possível notar que há tratamentos que diferem dos demais.\\\n\n## Ajustar o modelo para ANOVA\n\nPara realizar a ANOVA é preciso ajustar um modelo (`lm`). Isso é necessário para que os resíduos possam ser aplicados nos testes para verificação das premissas da anova. O modelo será atribuído a um objeto.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- lm(count~spray, data = inseticida)\nsummary(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = count ~ spray, data = inseticida)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-8.333 -1.958 -0.500  1.667  9.333 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  14.5000     1.1322  12.807  < 2e-16 ***\nsprayB        0.8333     1.6011   0.520    0.604    \nsprayC      -12.4167     1.6011  -7.755 7.27e-11 ***\nsprayD       -9.5833     1.6011  -5.985 9.82e-08 ***\nsprayE      -11.0000     1.6011  -6.870 2.75e-09 ***\nsprayF        2.1667     1.6011   1.353    0.181    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.922 on 66 degrees of freedom\nMultiple R-squared:  0.7244,\tAdjusted R-squared:  0.7036 \nF-statistic:  34.7 on 5 and 66 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n### ANOVA\n\nUma vez definido o modelo, ele será utilizado como um argumento na função `anova`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: count\n          Df Sum Sq Mean Sq F value    Pr(>F)    \nspray      5 2668.8  533.77  34.702 < 2.2e-16 ***\nResiduals 66 1015.2   15.38                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nCom a análise de variância e interpretação da estatística \"*F*\" é possível dizer que dentre os tratamentos, há algum que difere estatisticamente dos demais.\\\n\\\n\n## Avaliação das premissas\n\n### Estratégia 1\n\nPrimeiro, será analisada a normalidade dos resíduos de maneira visual (função `hist`) e estatisticamente (função `shapiro.test`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(m1$residuals)\n```\n\n::: {.cell-output-display}\n![](Aula-7_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\nshapiro.test(m1$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  m1$residuals\nW = 0.96006, p-value = 0.02226\n```\n\n\n:::\n:::\n\n\nApesar do histograma possuir aspecto de normalidade, o teste de Shapiro-Wilk demonstra que os resíduos não possuem normalidade (valor de P = 0.02).\\\n\\\nA normalidade também pode ser avaliada visualmente em um gráifco Q-Q, com as funções `qqnorm` e `qqline`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(m1$residuals)\nqqline(m1$residuals)\n```\n\n::: {.cell-output-display}\n![](Aula-7_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nO gráfico Q-Q mostra que os pontos desviam da linha de normalidade apenas nas regiões extremas, o que justifica o fato do teste de Shapiro-Wilk ter rejeitado a hipótese de normalidade dos resíduos.\\\n\\\n\\\nEm sequência, com o teste de Bartlett (`bartlett.test`), será avaliada a homogeneidade das variâncias entre os grupos:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbartlett.test(count ~ spray,\n              data = inseticida)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  count by spray\nBartlett's K-squared = 25.96, df = 5, p-value = 9.085e-05\n```\n\n\n:::\n:::\n\n\nO teste de Bartlett demonstra que as variâncias são heterogêneas, pois valor de P é menor que 0.01.\n\n### Estratégia 2\n\nUsando o pacote **`performance`**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_normality(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: Non-normality of residuals detected (p = 0.022).\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_heteroscedasticity(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: Heteroscedasticity (non-constant error variance) detected (p < .001).\n```\n\n\n:::\n:::\n\n\nO testes `check_normality` e `check_heteroscedasticity` resultaram em não normalidade dos resíduos e heterocedasticidade entre os grupos.\n\n### Estratégia 3\n\nCom o pacote **`DHARMa`**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(simulateResiduals(m1))\n```\n\n::: {.cell-output-display}\n![](Aula-7_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nDa mesma forma que as estratégias anteriores, aqui observa-se falta de normalidade e homogeneidade entre as variâncias dos grupos.\n\n## Transformação dos dados\n\nDiante dos resultados obtidos, conclui-se que o conjunto de dados não atende as pressuposições da ANOVA, logo é necessário definir uma estratégia para prosseguir na análise dos dados. É possível realizar transformações da variável resposta, adotar um teste não-paramétrico (por exemplo, teste de Kruskal-Wallis), ou utilizar um modelo linear generalizado (Generalized Linear Model - GLM). A seguir, são apresentados exemplos de como se adotar cada estratégia:\n\n### Alternativa 1 - Raiz quadrada\n\nOs dados serão transformados com a função `sqrt` e a coluna da variável resposta será substituída com os novos valores:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninseticida <- inseticida %>% \n  mutate(count2 = sqrt(count))\n\nglimpse(inseticida)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 72\nColumns: 3\n$ count  <dbl> 10, 7, 20, 14, 14, 12, 10, 23, 17, 20, 14, 13, 11, 17, 21, 11, …\n$ spray  <fct> A, A, A, A, A, A, A, A, A, A, A, A, B, B, B, B, B, B, B, B, B, …\n$ count2 <dbl> 3.162278, 2.645751, 4.472136, 3.741657, 3.741657, 3.464102, 3.1…\n```\n\n\n:::\n:::\n\n\n#### Análise visual dos dados transformados\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninseticida %>%\n  ggplot(aes(spray, count2))+\n  geom_boxplot(width = 0.5)\n```\n\n::: {.cell-output-display}\n![](Aula-7_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nVisualmente, é possível dizer que, possivelmente, os dados transformados agora possuem normalidade e homocedasticidade, pois os valores de mediana tendem a se encontrar nos centros da caixas e essas tem tamanho mais ou menos similar entre si.\n\n#### Ajuste do novo modelo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2 <- lm(count2 ~ spray,\n         data = inseticida)\n\nsummary(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = count2 ~ spray, data = inseticida)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.24486 -0.39970 -0.01902  0.42661  1.40089 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   3.7607     0.1814  20.733  < 2e-16 ***\nsprayB        0.1160     0.2565   0.452    0.653    \nsprayC       -2.5158     0.2565  -9.807 1.64e-14 ***\nsprayD       -1.5963     0.2565  -6.223 3.80e-08 ***\nsprayE       -1.9512     0.2565  -7.606 1.34e-10 ***\nsprayF        0.2579     0.2565   1.006    0.318    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.6283 on 66 degrees of freedom\nMultiple R-squared:  0.7724,\tAdjusted R-squared:  0.7552 \nF-statistic:  44.8 on 5 and 66 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n#### ANOVA com os novos dados\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova (m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: count2\n          Df Sum Sq Mean Sq F value    Pr(>F)    \nspray      5 88.438 17.6876  44.799 < 2.2e-16 ***\nResiduals 66 26.058  0.3948                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nMesmo após transformação, os dados continuem apresentando diferença significativa, ou seja, há pelo menos uma média que difere das demais.\n\n#### Avaliação das premissas - Normalidade\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(m2$residuals)\n```\n\n::: {.cell-output-display}\n![](Aula-7_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(m2$residuals)\nqqline(m2$residuals)\n```\n\n::: {.cell-output-display}\n![](Aula-7_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(m2$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  m2$residuals\nW = 0.98721, p-value = 0.6814\n```\n\n\n:::\n:::\n\n\nVisual e estatisticamente, conclui-se que os resíduos do conjunto de dados transformados possuem distribuição normal.\n\n#### Avaliação das premissas - Homocedasticidade\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbartlett.test(count2 ~ spray,\n              data = inseticida)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  count2 by spray\nBartlett's K-squared = 3.7525, df = 5, p-value = 0.5856\n```\n\n\n:::\n:::\n\n\nApós a transformação, é possível dizer que há homogeneidade de variâncias entre os grupos.\n\n#### Avaliação das premissas - Pacote `performance`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_normality(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOK: residuals appear as normally distributed (p = 0.681).\n```\n\n\n:::\n\n```{.r .cell-code}\ncheck_heteroscedasticity(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOK: Error variance appears to be homoscedastic (p = 0.854).\n```\n\n\n:::\n:::\n\n\n#### Avaliação das premissas - Pacote **`DHARMa`**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(simulateResiduals(m2))\n```\n\n::: {.cell-output-display}\n![](Aula-7_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nApós os vários testes realizados, temos confiança que os dados transformados possuem distribuição normal e homogeneidade das variâncias. Logo, é possível realizar comparações de médias.\n\n### Comparação de médias\n\n#### Para o modelo 1 - não transformado (não atendendo às pressuposições):\n\nApenas à título de curiosidade, será feita uma comparação de médias com base nos valores originais. O que não é correto, uma vez que esses não satisfazem as pressuposições da ANOVA.\\\nPara isso, a função `emmeans`, indicando o modelo (m1) e os tratamentos (spray), será atribuída a um objeto.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1_medias <- emmeans(m1, ~ spray)\nplot(m1_medias)\n```\n\n::: {.cell-output-display}\n![](Aula-7_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nO gráfico gerado mostra que para essa situação, os tratamentos tendem a formar dois grupos de eficiência.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmultcomp::cld(m1_medias)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n spray emmean   SE df lower.CL upper.CL .group\n C       2.08 1.13 66   -0.177     4.34  1    \n E       3.50 1.13 66    1.240     5.76  1    \n D       4.92 1.13 66    2.656     7.18  1    \n A      14.50 1.13 66   12.240    16.76   2   \n B      15.33 1.13 66   13.073    17.59   2   \n F      16.67 1.13 66   14.406    18.93   2   \n\nConfidence level used: 0.95 \nP value adjustment: tukey method for comparing a family of 6 estimates \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n:::\n\n\nO que é comprovado estatisticamente pela comparação de médias, utilizando o teste de Tukey.\n\n#### Para o modelo 2 - transformado\n\nPara os dados transformados, serão aplicados os mesmos passos descritos acima:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2_medias <- emmeans(m2, ~ spray)\nplot(m2_medias)\n```\n\n::: {.cell-output-display}\n![](Aula-7_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nVisualmente, é possível dizer que os inseticidas formam três grupos distintos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmultcomp::cld(m2_medias)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n spray emmean    SE df lower.CL upper.CL .group\n C       1.24 0.181 66    0.883     1.61  1    \n E       1.81 0.181 66    1.447     2.17  12   \n D       2.16 0.181 66    1.802     2.53   2   \n A       3.76 0.181 66    3.399     4.12    3  \n B       3.88 0.181 66    3.514     4.24    3  \n F       4.02 0.181 66    3.656     4.38    3  \n\nConfidence level used: 0.95 \nP value adjustment: tukey method for comparing a family of 6 estimates \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n:::\n\n\nCom a média transformada, o teste de Tukey agrupa os tratamentos em 3 grupos distintos, logo houve melhor discriminação. Com isso, concluímos que, em comparação aos demais, o inseticida C foi o mais eficiente, pois apresentou menor número de insetos contados. Em seguida, os inseticidas E e D apresentaram desempenho intermediário. Por fim, há um grupo com os inseticidas menos eficientes, nesse caso, contendo os tratamentos A, B e F.\n\n#### Alternativas para visualização das comparações de médias\n\n#### Função `pwpm`:\n\nA função `pwpm` (`emmeans`) constrói uma matriz de valores de probabilidade, onde são apresentadas as comparações entre tratamentos, par a par. Nas diagonais, entre colchetes, são apresentados os valores de média de cada tratamento.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npwpm(m2_medias)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       A      B      C      D      E      F\nA [3.76] 0.9975 <.0001 <.0001 <.0001 0.9145\nB -0.116 [3.88] <.0001 <.0001 <.0001 0.9936\nC  2.516  2.632 [1.24] 0.0081 0.2513 <.0001\nD  1.596  1.712 -0.919 [2.16] 0.7366 <.0001\nE  1.951  2.067 -0.565  0.355 [1.81] <.0001\nF -0.258 -0.142 -2.774 -1.854 -2.209 [4.02]\n\nRow and column labels: spray\nUpper triangle: P values   adjust = \"tukey\"\nDiagonal: [Estimates] (emmean) \nLower triangle: Comparisons (estimate)   earlier vs. later\n```\n\n\n:::\n:::\n\n\n#### Função `pwpp`:\n\nA função `pwpp` (`emmeans`) constrói uma plotagem de valores de probabilidade associados as comparações pareadas das médias marginais estimadas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npwpp (m2_medias)\n```\n\n::: {.cell-output-display}\n![](Aula-7_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n#### Função `pairs`:\n\nA função `pairs` apresenta os contrastes ortogonais dos valores de médias dos tratamentos, associados aos valores de probabilidade.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(m2_medias)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast estimate    SE df t.ratio p.value\n A - B      -0.116 0.257 66  -0.452  0.9975\n A - C       2.516 0.257 66   9.807  <.0001\n A - D       1.596 0.257 66   6.223  <.0001\n A - E       1.951 0.257 66   7.606  <.0001\n A - F      -0.258 0.257 66  -1.006  0.9145\n B - C       2.632 0.257 66  10.259  <.0001\n B - D       1.712 0.257 66   6.675  <.0001\n B - E       2.067 0.257 66   8.058  <.0001\n B - F      -0.142 0.257 66  -0.554  0.9936\n C - D      -0.919 0.257 66  -3.584  0.0081\n C - E      -0.565 0.257 66  -2.201  0.2513\n C - F      -2.774 0.257 66 -10.813  <.0001\n D - E       0.355 0.257 66   1.383  0.7366\n D - F      -1.854 0.257 66  -7.229  <.0001\n E - F      -2.209 0.257 66  -8.612  <.0001\n\nP value adjustment: tukey method for comparing a family of 6 estimates \n```\n\n\n:::\n:::\n\n\n### Alternativa 1.2 - Transformação de Box--Cox\n\nPara tentar sanar o problema da falta de normalidade e/ou heterocedasticidade, é possível utilizar um segundo tipo de transformação, neste caso a transformação de Box-Cox.\n\nA transformação de Box-Cox se baseia na seguinte equação:\n\n$y_{(\\lambda)} = (y^{\\lambda} - 1)/ \\lambda$\n\nOnde, y representa a variável resposta original; $y_{(\\lambda)}$ é a variável resposta transformada; e lambda (𝛌) é o parâmetro de transformação, variando entre - ∞ e + ∞.\n\n\\\nPara conduzir essa transformação, é utilizada a função `boxcox` (pacote `MASS`). A função calcula e identifica o valor 𝛌 ótimo para um determinado conjunto de dados (onde o valor de Y é máximo).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MASS)\n\nb <- boxcox(lm(inseticida$count + 0.1 ~ 1))\n```\n\n::: {.cell-output-display}\n![](Aula-7_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlambda <- b$x [which.max(b$y)]\nlambda\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4242424\n```\n\n\n:::\n:::\n\n\nCom os comandos acima é possível determinar na equação (b) o valor de 𝛌 (no eixo x), cujo valor de y é máximo. Logo, para o conjunto em análise, 𝛌 ≅ 0.42.\n\n#### Transformando os dados com Box-Cox\n\nCom o valor calculado acima, realiza-se a transformação de Box-Cox:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninseticida$count3 <-(inseticida$count ^ lambda - 1) / lambda\n```\n:::\n\n\n\\\nNovo modelo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3 <- lm(count3 ~ spray,\n         data = inseticida)\n```\n:::\n\n\n\\\nAvaliação de normalidade e homogeneidade de variâncias entre os grupos:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(inseticida$count3)\n```\n\n::: {.cell-output-display}\n![](Aula-7_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm (m3$residuals)\nqqline (m3$residuals)\n```\n\n::: {.cell-output-display}\n![](Aula-7_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n\n```{.r .cell-code}\nshapiro.test(m3$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  m3$residuals\nW = 0.98873, p-value = 0.7723\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbartlett.test(count3 ~ spray,\n              data = inseticida)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  count3 by spray\nBartlett's K-squared = 5.7412, df = 5, p-value = 0.3322\n```\n\n\n:::\n:::\n\n\nCom a transformação de Box-Cox, os dados passaram a possuir normalidade e homocedasticidade, satisfazendo as pressuposições da ANOVA. Em seguida poderiam ser feitos ANOVA e comparação de médias como já demonstrado anteriormente.\n\n### Alternativa 2 - Usar um teste não paramétrico\n\nComo a variável resposta do conjunto de dados em estudo é do tipo numérica discreta e não pareada, é adotado o teste de Kruskal Wallis.\\\n\n### `kruskal.test`\n\nEssa função faz um teste de Kruskal Wallis e é útil apenas para informar se há alguma diferença estatística significativa entre os grupos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal.test(count ~ spray,\n             data = inseticida)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  count by spray\nKruskal-Wallis chi-squared = 54.691, df = 5, p-value = 1.511e-10\n```\n\n\n:::\n:::\n\n\n### `kruskal` (pacote `agricolae`)\n\nAlém de realizar o teste de Kruskal Wallis, faz a comparação *post hoc* utilizando o critério da diferença menos significativa de Fisher.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(agricolae)\n\nKWT <- kruskal(inseticida$count,\n               inseticida$spray,\n               group = TRUE)\nKWT\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$statistics\n     Chisq Df      p.chisq  t.value      MSD\n  54.69134  5 1.510845e-10 1.996564 8.462804\n\n$parameters\n            test p.ajusted           name.t ntr alpha\n  Kruskal-Wallis      none inseticida$spray   6  0.05\n\n$means\n  inseticida.count     rank      std  r Min Max   Q25  Q50   Q75\nA        14.500000 52.16667 4.719399 12   7  23 11.50 14.0 17.75\nB        15.333333 54.83333 4.271115 12   7  21 12.50 16.5 17.50\nC         2.083333 11.45833 1.975225 12   0   7  1.00  1.5  3.00\nD         4.916667 25.58333 2.503028 12   2  12  3.75  5.0  5.00\nE         3.500000 19.33333 1.732051 12   1   6  2.75  3.0  5.00\nF        16.666667 55.62500 6.213378 12   9  26 12.50 15.0 22.50\n\n$comparison\nNULL\n\n$groups\n  inseticida$count groups\nF         55.62500      a\nB         54.83333      a\nA         52.16667      a\nD         25.58333      b\nE         19.33333     bc\nC         11.45833      c\n\nattr(,\"class\")\n[1] \"group\"\n```\n\n\n:::\n:::\n\n\nO teste não paramétrico resultou na mesma resposta que o modelo com os dados transformados (modelo m2).\\\n\n### Alternativa 3 - modelo linear generalizado (Generalized Linear Model - GLM)\n\nO uso de modelos lineares generalizados pode ser visto como um método de transformação mais bonito e elegante que os apresentados anteriormente, mesmo que ambas as metodologias estejam corretas.\\\nCom o GLM, o modelo (a função) mais apropriado é definido de acordo com a distribuição dos dados em análise.\\\nNeste exemplo, será aplicada uma distribuição de Poisson, já que a variável resposta é do tipo numérica discreta.\n\nA função `glm` é utilizada para ajustar o modelo linear, onde é preciso indicar a variável resposta, a variável independente, a família de distribuição de probabilidade e o conjunto de dados utilizado.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm4 <- glm(count ~ spray,\n          family = poisson,\n          data = inseticida)\n\nsummary(m4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = count ~ spray, family = poisson, data = inseticida)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  2.67415    0.07581  35.274  < 2e-16 ***\nsprayB       0.05588    0.10574   0.528    0.597    \nsprayC      -1.94018    0.21389  -9.071  < 2e-16 ***\nsprayD      -1.08152    0.15065  -7.179 7.03e-13 ***\nsprayE      -1.42139    0.17192  -8.268  < 2e-16 ***\nsprayF       0.13926    0.10367   1.343    0.179    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 409.041  on 71  degrees of freedom\nResidual deviance:  98.329  on 66  degrees of freedom\nAIC: 376.59\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(m4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel: poisson, link: log\n\nResponse: count\n\nTerms added sequentially (first to last)\n\n      Df Deviance Resid. Df Resid. Dev\nNULL                     71     409.04\nspray  5   310.71        66      98.33\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\nAnova(m4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table (Type II tests)\n\nResponse: count\n      LR Chisq Df Pr(>Chisq)    \nspray   310.71  5  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n#### Verificação das pressuposições da ANOVA\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(simulateResiduals(m4))\n```\n\n::: {.cell-output-display}\n![](Aula-7_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\n#### Comparação de médias --- continuar\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm4_medias <- emmeans(m4, ~ spray,\n                     type =  \"response\") #para apresentar as médias no formato original, não em log#\n\nm4_medias\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n spray  rate    SE  df asymp.LCL asymp.UCL\n A     14.50 1.099 Inf     12.50     16.82\n B     15.33 1.130 Inf     13.27     17.72\n C      2.08 0.417 Inf      1.41      3.08\n D      4.92 0.640 Inf      3.81      6.35\n E      3.50 0.540 Inf      2.59      4.74\n F     16.67 1.179 Inf     14.51     19.14\n\nConfidence level used: 0.95 \nIntervals are back-transformed from the log scale \n```\n\n\n:::\n\n```{.r .cell-code}\ncld(m4_medias)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n spray  rate    SE  df asymp.LCL asymp.UCL .group\n C      2.08 0.417 Inf      1.41      3.08  1    \n E      3.50 0.540 Inf      2.59      4.74  12   \n D      4.92 0.640 Inf      3.81      6.35   2   \n A     14.50 1.099 Inf     12.50     16.82    3  \n B     15.33 1.130 Inf     13.27     17.72    3  \n F     16.67 1.179 Inf     14.51     19.14    3  \n\nConfidence level used: 0.95 \nIntervals are back-transformed from the log scale \nP value adjustment: tukey method for comparing a family of 6 estimates \nTests are performed on the log scale \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n:::\n\n\n## Experimento Fatorial - 2ANOVA\n\n### Importação e visualização dos dados\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFAT <- gsheet2tbl(\"https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=2023059672\")\n```\n:::\n\n\nAo aplicar o comando `theme_set (theme_bw())`, todos os gráficos gerados a partir da inserção deste comando terão o tema designado, no caso \"*theme_bw*\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheme_set(theme_bw())\n\nFAT %>%\n  ggplot(aes(treat, severity, color = factor(dose)))+\n  geom_jitter(width = 0.1)\n```\n\n::: {.cell-output-display}\n![](Aula-7_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n\n```{.r .cell-code}\nFAT %>%\n  ggplot(aes(treat, severity, color = factor(dose)))+\n  geom_jitter()+\n  facet_wrap(~dose)\n```\n\n::: {.cell-output-display}\n![](Aula-7_files/figure-html/unnamed-chunk-43-2.png){width=672}\n:::\n:::\n\n\nAcima, foram apresentados dois gráficos para visualização dos dados. A primeira opção, faz uso de cores para apresentar as respostas associados aos níveis do fator dose, enquanto os níveis do fator \"treat\" são apresentados no eixo x.\\\nJá a segunda opção, faz uso da função `facet_wrap`, em que são construídos dois gráficos, um para cada nível do fator dose.\n\n### Ajustar o modelo fatorial\n\nPara construir o modelo para experimento com arranjo fatorial ainda será utilizada a função `lm`. No entanto, como dois ou mais fatores serão avaliados é preciso incluir as outras variáveis independentes no modelo. Dessa forma, a fórmula seria baseada em: variável `resposta`**\\~**`varíavel indepedente_1`**\\***`varíavel indepedente_2`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmf <- lm (severity ~ treat*dose,\n          data = FAT)\n```\n:::\n\n\n### ANOVA com 2 fatores\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(mf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: severity\n           Df   Sum Sq  Mean Sq F value    Pr(>F)    \ntreat       1 0.113232 0.113232  30.358 4.754e-05 ***\ndose        1 0.073683 0.073683  19.755 0.0004077 ***\ntreat:dose  1 0.072739 0.072739  19.502 0.0004326 ***\nResiduals  16 0.059678 0.003730                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nA análise de variância nos mostra que há diferença entre as médias dos tratamentos (treat, F =4.754e-05), entre as médias das doses (dose, F = 0.0004077), e que também há diferenças significativas na interação tratamento\\*dose (treat:dose, F = 0.0004326).\n\nPortanto, como há interações entre fatores, será preciso decompor as médias e realizar comparações para os níveis das doses dentro do fator tratamento, e dos níveis do tratamentos dentro do fator dose.\n\n### Verificação das premissas - `DHARMa`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(simulateResiduals(mf))\n```\n\n::: {.cell-output-display}\n![](Aula-7_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\nOs resultados obtidos pelo pacote `DHARMa` demonstram que os dados seguem distribuição normal e há homogeneidade de variância entre os grupos.\n\n### Comparação de médias\n\nPara comparação de médias, também será utilizada a função `emmeans`, e para análise de um fator dentro de outro é preciso indicar a ordem dos fatores, separado por uma barra ( **\\|** ).\n\n#### Comparação dos níves do tratamento dentro dos níveis da dose\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmf_medias <- emmeans(mf, ~ treat | dose)\ncld(mf_medias)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndose = 0.5:\n treat        emmean     SE df lower.CL upper.CL .group\n Tebuconazole 0.0210 0.0273 16 -0.03690   0.0789  1    \n Ionic liquid 0.2921 0.0273 16  0.23420   0.3500   2   \n\ndose = 2.0:\n treat        emmean     SE df lower.CL upper.CL .group\n Tebuconazole 0.0202 0.0273 16 -0.03768   0.0781  1    \n Ionic liquid 0.0501 0.0273 16 -0.00781   0.1080  1    \n\nConfidence level used: 0.95 \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n:::\n\n\n#### Comparação dos níves da dose dentro dos níveis do tratamento\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmf_medias <- emmeans(mf, ~ dose | treat) \ncld(mf_medias)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntreat = Ionic liquid:\n dose emmean     SE df lower.CL upper.CL .group\n  2.0 0.0501 0.0273 16 -0.00781   0.1080  1    \n  0.5 0.2921 0.0273 16  0.23420   0.3500   2   \n\ntreat = Tebuconazole:\n dose emmean     SE df lower.CL upper.CL .group\n  2.0 0.0202 0.0273 16 -0.03768   0.0781  1    \n  0.5 0.0210 0.0273 16 -0.03690   0.0789  1    \n\nConfidence level used: 0.95 \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n:::\n",
    "supporting": [
      "Aula-7_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}